# Generated by Django 3.1.4 on 2020-12-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201225_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.FileField(upload_to='media/'),
        ),
    ]
