# Generated by Django 3.1.4 on 2020-12-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201225_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(to='mainapp.Product'),
        ),
    ]
