# Generated by Django 3.1.4 on 2020-12-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_data',
        ),
    ]
