# Generated by Django 3.1.4 on 2020-12-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_min_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
