# Generated by Django 3.1.4 on 2020-12-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_product_product_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
